### PR TITLE
Remove user image

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR removes the docker files for the user (notebook) image, as the user image is now provided by the separate https://github.com/malariagen/datalab-image repository.

Also updates the base image for the hub dockerfile, which I believe is needed to ensure both hub and user images are running the same version of jupyterhub (0.9.x).

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @slejdops, @idwright, this PR captures some changes I'm proposing regarding how we set up and manage the user image for MalariaGEN DataLab deployments.

The main change is that I've moved the user image definition out to a separate repo - https://github.com/malariagen/datalab-image. That repo is designed to work with repo2docker, and has continuous integration setup to automatically build a docker image and push to dockerhub. Currently there is one image built, see the [cggh/malariagen-datalab](https://cloud.docker.com/u/cggh/repository/docker/cggh/malariagen-datalab) repo on dockerhub.

The idea in all of this is (1) to reuse some cond environment definitions that we are using also for local environment installations, thus minimising the number of different environment definitions we are managing, and (2) to bring us a bit closer to the way that pangeo are moving, which is making use of binder.

Happy to talk all this through in the new year. In particular, although I've got the image building and pushing to dockerhub successfully, I'm getting errors locally and when trying to run via mybinder.org, so there may be some details to work out.

**Comment by alimanfoo** [comment]
Thanks for merging @slejdops.

Btw Circle CI has successfully build an image and pushed to docker hub, image is "cggh/malariagen-datalab:123fb658be". I'm just testing it locally now.

I didn't know how to specify which user image should be used when deploying jupyterhub, so apologies if I missed some configuration that should have been updated.

**Comment by alimanfoo** [comment]
Local testing of the cggh/malariagen-datalab:123fb658be image looks good, I can get either jupyter notebook or jupyter lab running.

**Comment by alimanfoo** [comment]
I've also run this via the [pangeo binderhub](https://binder.pangeo.io/) ([launch](https://binder.pangeo.io/v2/gh/malariagen/datalab-image/master)) and that works nicely too. Dask clusters launch fine, and I've run the [dask-array](https://github.com/pangeo-data/example.pangeo.io-deploy/blob/staging/deployments/example.pangeo.io/image/dask-array.ipynb) and [xarray-data](https://github.com/pangeo-data/example.pangeo.io-deploy/blob/staging/deployments/example.pangeo.io/image/xarray-data.ipynb) notebooks via dask clusters, so all looks good. I've also run a test using scikit-allel and the Ag1000G data we have in GCS, again via dask cluster, again all looks good :smile:.

**Comment by slejdops** [comment]
I have just deployed the new image to Google cloud,
getting the followingh error
`Error: failed to start container "notebook": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"binder/./start\": stat binder/./start: no such file or directory"`

**Comment by alimanfoo** [comment]
BTW ere's the [scikit-allel](https://gist.github.com/alimanfoo/5c90c83f1906983693439777c4706509) notebook I ran on binder.pangeo.io.

**Comment by alimanfoo** [comment]
> I have just deployed the new image to Google cloud,
> getting the followingh error
> `Error: failed to start container "notebook": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"binder/./start\": stat binder/./start: no such file or directory"`

Sorry @slejdops, don't know what's going on here. 

Did you upgrade the hub too? Don't know if the error is anything to do with this, but I think it's necessary to upgrade the hub image to make sure versions of jupyterhub on the hub and inside the user image match. I included an upgrade to the hub base image in this PR.

**Pull request merged**
